export const ProductData = [
  {
    id: 1,
    Title: "hello 1",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 2,
    Title: "hello 2",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 3,
    Title: "hello 3",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 4,
    Title: "hello 4",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 5,
    Title: "hello 5",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 6,
    Title: "hello 6",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 7,
    Title: "hello 7",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 8,
    Title: "hello 8",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 9,
    Title: "hello 9",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 10,
    Title: "hello 10",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 11,
    Title: "hello 11",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
  {
    id: 12,
    Title: "hello 12",
    img: "./components/image/spaghetti.jpg",
    price: "250$",
    Des: "article est babel",
    cat: "mug",
  },
];

export default ProductData;
